name: CD

on:
  pull_request:
    types: [closed]

env:
  AWS_REGION:    ${{ secrets.AWS_REGION }}
  ECR_REGISTRY:  ${{ vars.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}

jobs:
  promote-and-deploy:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main'
      
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull, Retag & Push Latest
        run: |
          TAG=${{ github.sha }}
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          docker tag \
            $ECR_REGISTRY/$ECR_REPOSITORY:$TAG \
            $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest